services:
  - type: web
    name: forensic-video-analysis
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
