services:
  - type: web
    name: forensic-video-analysis
    env: python
    plan: free
    region: ohio
    branch: main
    
    # OPTIMIZED BUILD COMMAND
    buildCommand: |
      echo "🚀 Starting bulletproof build process..."
      apt-get update
      apt-get install -y \
        ffmpeg \
        libsm6 \
        libxext6 \
        libgl1-mesa-glx \
        libjpeg-dev \
        libpng-dev \
        zlib1g-dev
      apt-get clean
      rm -rf /var/lib/apt/lists/*
      
      echo "📦 Installing Python dependencies..."
      pip install --upgrade pip setuptools wheel
      
      # Install Pillow first with specific flags
      pip install --no-cache-dir --timeout=300 --only-binary=all pillow==9.5.0
      
      # Install rest of requirements
      pip install --no-cache-dir --timeout=300 -r requirements.txt
      
      echo "✅ Build completed successfully!"
    
    # START COMMAND
    startCommand: hypercorn asgi:application --bind 0.0.0.0:$PORT --workers 1
    
    # ENVIRONMENT VARIABLES
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
    
    # HEALTH CHECK
    healthCheckPath: /health
    
    autoDeploy: true
